---
title: "tes"
author: 
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    number_sections: true
    theme: flatly
    highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load}

## 2007 apms analysis ##
### new workflow ###

# clear enviroment 
rm(list = ls())

#install.packages if not already
# load libraries
pacman::p_load(skimr,
               naniar,
               gtsummary,
               finalfit,
               knitr,
               tidyverse,
               haven,
               ggplot2,
               forcats,
               janitor,
               survey,
               srvyr,
               questionr,
               ggpubr,
               reprex)

# check packages
pacman::p_loaded()

# Read in 2007
source_pms07 <- haven::read_sav("07 analysis/apms07arch.sav", 
                                user_na = TRUE) %>%
  as_factor() 
```

```{r subset}
# Variables of interest subset 2007
subset_pms07 <- source_pms07 %>% 
  dplyr::select("pserial","trtment","eqvinc5","diag","CISRFOUR","ResSex"                 ,"Health6","Language","Age10yr",
                "Age20yr","ETHNIC5","Origin","EDQUAL5","AnyQuals",
                "HiQuals","ResMarDF",
                "DVILO4a","DVPrac","Care1","Care2","Care3","Care4",
                "Care5","Everwk","yearjbl","JbReas","Looked",
                "YInAct","LookStop","LookSto2","Stat","Solo",
                "HrsWeek","PTWkHour","EmpStY","LookNot1","LookNot2",
                "LookNot3","DVLastWk","NotWk","WkShel1","HrsWork",
                "LookSto3","DiffJob","WkShel2","WkShel3","SEmpStY",
                "LookNow","LookAtAl","JobstM","EmpNo","Manage",
                "FtPtWk","NotWk","SEG","SC","SrcInc1","SrcInc2",
                "SrcInc3","SrcInc4","SrcInc5","SrcInc6","Gross4",
                "Gross4a","Ten1","LLord","SF6","SF7","SF9","SF11",
                "SF12","CONHOMD","IMon","FollUpGrp",
                "eligible","Stage2","Origin","DVPrac","Care1","Care2",
                "Care3","Care4","Care5","Medic","CnslHav","CnslTak",
                "CnslLng","DocYear","DocPsyc","PMatNum","DocTalk",
                "DocWeeks","InWhy","OutWhy","DayY","DayWht1",
                "DayWht2","DayWht3","DayWht4","CC2aY",
                "CC2Y1","CC2Y2","CC2Y3","CC2Y5","CC2Y6","CC2Y7",
                "CC2Y8","CC2Y9","MentHos","Ten1","Gross4a","qimd",
                "gor06","newsha","SF1","Happy","tenure","newten",
                "hhdtype","DISsex","DISeth","DISrel","DISAge",
                "DISmen","DISphy",
                "DISsori","CISRFOUR","panic","GAD","madd","OCD",
                "phob","dep","neurotic","nosymp","numdis",
                "PTSDever","MajorT16","PTSDcom","PTSDPos",
                "suicthwk","suicthyr","suicthlf","DSHlife",
                "suicatwk","suicatyr","suicatlf","DSHtry","suihfri",
                "suihhos","suihcom","suihhel","suihoth","DSH5",
                "DSHharm","DSH9","DSH10","PsycProb","Psycdis",
                "Psycdis_wt","BPDPH2","bdpd_wt","ASPDPH2","aspd_wt",
                "DVADHD1","DVADHD2","DVADHD4","scoff2","EDImpact",
                "bmigp4","DVAudit1","AUDITgp","DRNKPROB","SADQCSC",
                "SADQGP","AUDSAD2","Cannever","Cannyear","AMPHEVER",
                "AMPHYEAR","COCAEVER","CRACEVER","CRACYEAR",
                "ECSTEVER","ECSTYEAR","HEROEVER","HEROYEAR",
                "ACIDEVER","ACIDYEAR","MUSHEVER","MUSHYEAR",
                "METHEVER","METHYEAR","TRANEVER","TRANYEAR",
                "AMYLEVER","AMYLYEAR","ANABEVER",
                "ANABYEAR","GLUEEVER","GLUEYEAR","DRUGEVER",
                "DRUGYEAR","DRUGDEP",
                "DRUGDEP2","GamYR","dsmscgr","dsmprob","dsmpath",
                "numdiag","numdiag4","LCA","cluster1","cluster2",
                "cluster3","cluster4","cluster5","cluster6",
                "MedPsyc","MedDep","MedHyp","MedAnx","MedADHD",
                "anymed","Doc2Wks","DocPsyc","INQTRMEN","OUTQTRME",
                "PSYCTHER","COGTHER","ARTTHER","SOCTRAIN","MARITHER"
                ,"SEXTHER","COUNSEL","OTHTHER","OTHTHER","anyther",
                "trtment","DAYCOMYR","PSYTRTYR","PSYLGTYR",
                "CPNYR","CLDNYR","OTHNSEYR","SOCWRKYR","CPNYR",
                "ERI3","SFQA","SFQB","SFQC","SFQD",
                "SFQE","SFQF","SFQG","SFQH","DLSS4","DLSS5",
                "PrimGrp","ChldInst","LACare","BothMaPa",
                "YNotBoth","MaOrPa","AnyChild","NoChild",
                "InDebt1","InDebt6",
                "SFHELPYR","HMHELPYR","OREACHYR","anyccar","anyhlca"
                ,"anydaca","wt_ints1","ipsu_0714","istrata_0714",
                "eqvinc5","ptsdlong","PTSDarms","MajorT16","ResAge",
                "cluster","area") %>%
  janitor::clean_names() %>%
  janitor::remove_empty("cols") %>%
  janitor::remove_empty("rows") %>%
  mutate(across(where(is.factor), as.character))

head(subset_pms07, 5)


# Arrange alphabetically and make 'colnames' lowercase

subset_pms07 <-subset_pms07[,order(colnames(subset_pms07))] %>% rename_all(tolower)

# Check names
head(subset_pms07, 5)
table(subset_pms07$diag)
class(subset_pms07$diag)

# remove source df
remove(source_pms07)

table(subset_pms07$diag)
```

```{r convert}

# Convert unwanted levels to NA
# write out all the offending strings of different NAs used
na_strings <- c("No answer/refused",
                "Don't know",
                "Missing data",
                "Proxy",
                "Item not applicable",
                "No disord",
                "Don't know",
                "Item not applicable")

#Then you write ~.x %in% na_strings - which reads as “does this 
#value occur in the list of NA strings”.
subset_pms07 %>%
  replace_with_na_all(condition = ~.x %in% na_strings)


# convert df back to factor 
subset_pms07 %>% mutate_if(is.character, as.factor)

```

```{r fct lvls}
# Renaming factor levels dplyr
subset_pms07$diag <- recode_factor(subset_pms07$diag,
                                   "MAD" = "Mixed Anx & Dep",
                                   "GAD" = "Gen Anx & Dep",
                                   "sev dep ep" = "Sev Dep",
                                   "mild dep ep" = "Mild Dep",
                                   "mod dep ep" = "Mod Dep",
                                   "panic" = "Panic Dis",
                                   "social phob" = "Soc Phob",
                                   "Spec iso phob" = "Specific Phob",
                                   "No disord" = "None")

# Renaming factor levels dplyr
subset_pms07$eqvinc5 <- recode_factor(subset_pms07$eqvinc5, 
                                      "3rd quintile (>=16,195 <?24,700)" = "Third (16,195-24,700)",
                                      "highest quintile (>=?40,384)" = "Highest (>40,384)",
                                      "Lowest quintile (<?10,575)" = "Lowest (<10,575)",
                                      "2nd quintile (>=?24, 700 <?40,384)" = "Second (24,700-40,384)",
                                      "4th quintile (>=?10,575 <?16,195)" = "Fourth (10,575-16,195)")

# Renaming factor levels dplyr
subset_pms07$ethnic5 <- recode_factor(subset_pms07$ethnic5, 
                                      "South Asian (Indian, Pakistani or Bangladeshi)" = "South Asian")

# Renaming factor levels dplyr
subset_pms07$dvilo4a <- recode_factor(subset_pms07$dvilo4a, 
                                   "In employment not unpaid family worker" = "Employed")

# Renaming factor levels dplyr
subset_pms07$edqual5 <- recode_factor(subset_pms07$edqual5, 
                                      "No qualifications" = "None",
                                      "Teaching, HND, nursing" = "Vocaational*")

# Renaming factor levels dplyr
subset_pms07$trtment <- recode_factor(subset_pms07$trtment, 
                                      "no treatment" = "None",
                                      "medication only" = "Medication only",
                                      "counselling only" = "Counselling only",
                                      "both medication and counselling" = "Both")
```

```{r weight prep}
# change weights to numeric 
subset_pms07$wt_ints1 <- as.numeric(as.character(subset_pms07$wt_ints1)) # phase 1 weight
class(subset_pms07$wt_ints1) 
subset_pms07$psycdis_wt <- as.numeric(as.character(subset_pms07$psycdis_wt)) # weight to use with psycdis var
class(subset_pms07$psycdis_wt)
subset_pms07$bdpd_wt <- as.numeric(as.character(subset_pms07$bdpd_wt)) # Borderline personality disorder weight - use with bpdph2
class(subset_pms07$bdpd_wt)
subset_pms07$aspd_wt <- as.numeric(as.character(subset_pms07$aspd_wt))# Antisocial personality disorder weight - use with aspdph2
class(subset_pms07$aspd_wt)
subset_pms07$res_age <- as.numeric(as.character(subset_pms07$res_age))


# make weighted object of 07 
weight_pms07 <- svydesign(data = subset_pms07,
                          strata = ~cluster, #stratification variable
                          id = ~area, nest = TRUE, #Primary sampling unit variable. ID is where  we specify the variables that represent the clusters. PSU is sampled within each strata. Therefore, we must include nest equals TRUE because the cluster ids are nested within the strata
                          weights = ~wt_ints1) #Survey weight for all analyses except specialised ones for conditions. 

```

```{r overall descriptive tbl}
# Big desc table
subset_pms07 %>%
  select(age10yr, res_sex, diag, dvilo4a) %>%
  tbl_summary(by = age10yr) %>%
  add_overall() %>%
  add_n() %>%
  bold_labels()

```


```{r plott}
#####
#### Univariate Plots ####

# Age
ageuw <- subset_pms07 %>%
  ggplot(aes(x = (age10yr),
             y = prop.table(stat(count)),
             fill = (age10yr),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(aes(label = sprintf('%01.f (%.1f%%)', after_stat(count), after_stat(count / sum(count) * 100))), # show counts & %
            stat='count',
            position = position_dodge(.9),
            vjust = -1,
            size = 3) +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + # make y % and no decimal
  labs(title = "Unweighted Survey Makeup (2007) \n by Age Group", 
       x = 'Respondant Age', 
       y = 'Percentage',
       fill = 'Age Group',
       caption = "(Test Footnote 2021)") + # footnote
  annotate("text", x = 7, y = .2, size = 3, label = "n = 7,403") + # add total n = manually
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) # 0 = left, 0.5 = middle, 1 = right

# weighted age
agew <- ggsurvey(weight_pms07) + 
  (aes(x = (age10yr),
       y = prop.table(stat(count)),
       fill = (age10yr),
       label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(aes(label = sprintf('%01.f (%.1f%%)', after_stat(count), after_stat(count / sum(count) * 100))), # show counts & %
            stat='count',
            position = position_dodge(.9),
            vjust = -1,
            size = 3) +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + # make y % and no decimal
  labs(title = "Weighted Survey Makeup (2007) \n by Age Group", 
       x = 'Respondant Age', 
       y = 'Percentage',
       fill = 'Age Group',
       caption = "(Test Footnote 2021)") + # footnote
  annotate("text", x = 7, y = .2, size = 3, label = "n = 7,403") + # add total n = manually
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) # 0 = left, 0.5 = middle, 1 = right

# put plots together
agewt <- ggarrange(ageuw, agew,
                   ncol = 2, nrow = 2)
```

