---
title: "Test Clean & Explore of PMS '07"
author: "Michelle K Jamieson"
date: "11/06/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

install.packages("haven")
install.packages("tidyverse")
install.packages("knitr")
install.packages("skimr")
install.packages("visdat")
install.packages("psych")
install.packages("gmodels")
library(gmodels)
library(psych)
library(visdat)
library(skimr)
library(knitr)
library(haven)
library(tidyverse)

```

```{r}
# read in 2007 data 
psychmorb07 <- read_spss("pms07.sav")

# Subsetting
pm07.sub <- psychmorb07[,c("ResSex", "ResAge", "SF1", "Happy", 
                           "Health6", "Everwk", "Psycdis")]

# Change Labels
attr(pm07.sub$ResSex, "label") <- "Respondant Sex"
attr(pm07.sub$ResAge, "label") <- "Respondant Age"
attr(pm07.sub$SF1, "label") <- "General Health"
attr(pm07.sub$Happy, "label") <- "How Happy Are You?"
attr(pm07.sub$Health6, "label") <- "Mental Health Condition Mentioned"
attr(pm07.sub$Everwk, "label") <- "Ever Had a Paid Job"
attr(pm07.sub$Psycdis, "label") <- "Definitive Psychosis in Last Year"

colnames(pm07.sub)


# rename variables 
pm07.sub <- pm07.sub %>% rename(Sex = ResSex, Age = ResAge,
                                GenHeal = SF1, HowHap = Happy,
                                MenHeal = Health6, PaidJob = Everwk,
                                DefPsych = Psycdis) 
colnames(pm07.sub)

# Make NAs explicit 
pm07.sub = pm07.sub %>% mutate_if(is.factor,
                                  fct_explicit_na,
                                  na_level = "No Answer")

# mutate to factors and keep
cleanpm07 <- pm07.sub %>% 
  mutate(Sex = as_factor(Sex),
         Age = as_factor(Age),
         GenHeal = as_factor(GenHeal),
         HowHap = as_factor(HowHap),
         MenHeal = as_factor(MenHeal),
         PaidJob = as_factor(PaidJob),
         DefPsych = as_factor(DefPsych))
head(cleanpm07)

# look
summary(cleanpm07)
skim(cleanpm07)
vis_dat(cleanpm07)

describe(cleanpm07)

# descriptives for mental health condition mentioned x 
# def had psychosis condition in past year

# total no of people who mentioned having any mental health 
# condition by no of people who definetly had psychosis type
# condition in the past year (2006-2007)
cleanpm07 %>%
  group_by(MenHeal, DefPsych)%>%
  summarize(n=n())%>%
  kable()

# crosstab of people who mentioned having any mental health 
# condition by no of people who definetly had psychosis type
# condition in the past year (2006-2007)
cleanpm07 %>%
  group_by(MenHeal, DefPsych)%>%
  summarise(n=n())%>%
  spread(DefPsych, n)%>%
  kable()

# quick way to pull together row/column 
# frequencies and proportions mental health and 
# psychosis conditions vars
table(cleanpm07$MenHeal, cleanpm07$DefPsych)

# table frequency can also be called by using the ftable() command.

cpm07_table<- table(cleanpm07$MenHeal, cleanpm07$DefPsych) #define object w/table parameters for simple calling
ftable(cpm07_table)

# For row frequencies, 
margin.table(cpm07_table, 1) 

# For column frequencies
margin.table(cpm07_table, 2) 

# For proportion of the entire table, 
prop.table(cpm07_table)     #proportion of entire table

# For column proportions,
prop.table(cpm07_table, 2)  #proportion of entire column

# produces frequencies, and table, 
# row, & column proportions with a single command
CrossTable(cleanpm07$MenHeal, cleanpm07$DefPsych)




####
# descriptives for def had psychosis in past year x
# ever had a paid job 

#cleanpm07 %>%
#  group_by(DefPsych, PaidJob)%>%
#  summarize(n=n())%>%
#  kable()

#cleanpm07 %>%
#  group_by(DefPsych, PaidJob)%>%
#  summarise(n=n())%>%
#  spread(PaidJob, n)%>%
# kable()

#table(cleanpm07$DefPsych, cleanpm07$PaidJob)


# Creates really cool exploratory report of data set
# DataExplorer::create_report(cleanpm07)

```

