---
title: "2021_07_2007_new_workflow"
author: "Michelle K Jamieson"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    number_sections: true
    theme: flatly
    highlight: textmate
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load}
## 2021-06-28 ##
## 2007 apms analysis ##
### new workflow ###

# clear enviroment 
rm(list = ls())

#install.packages if not already
# load libraries
pacman::p_load(skimr,
       naniar,
       gtsummary,
       finalfit,
       knitr,
       tidyverse,
       haven,
       ggplot2,
       forcats,
       janitor,
       rmarkdown)

# check packages


# Read in 2007
source_pms07 <- haven::read_sav("apms07arch.sav", 
                                user_na = TRUE) %>%
  as_factor() 
```

```{r subset}
# Variables of interest subset 2007
subset_pms07 <- source_pms07 %>% 
  dplyr::select("pserial","trtment","eqvinc5","diag","CISRFOUR","ResSex","Health6","Language","Age10yr",
                "Age20yr","ETHNIC5","Origin","EDQUAL5","AnyQuals",
                "HiQuals","ResMarDF",
                "DVILO4a","DVPrac","Care1","Care2","Care3","Care4",
                "Care5","Everwk","yearjbl","JbReas","Looked",
                "YInAct","LookStop","LookSto2","Stat","Solo",
                "HrsWeek","PTWkHour","EmpStY","LookNot1","LookNot2",
                "LookNot3","DVLastWk","NotWk","WkShel1","HrsWork",
                "LookSto3","DiffJob","WkShel2","WkShel3","SEmpStY",
                "LookNow","LookAtAl","JobstM","EmpNo","Manage",
                "FtPtWk","NotWk","SEG","SC","SrcInc1","SrcInc2",
                "SrcInc3","SrcInc4","SrcInc5","SrcInc6","Gross4",
                "Gross4a","Ten1","LLord","SF6","SF7","SF9","SF11",
                "SF12","CONHOMD","IMon","FollUpGrp",
                "eligible","Stage2","Origin","DVPrac","Care1","Care2",
                "Care3","Care4","Care5","Medic","CnslHav","CnslTak",
                "CnslLng","DocYear","DocPsyc","PMatNum","DocTalk",
                "DocWeeks","InWhy","OutWhy","DayY","DayWht1",
                "DayWht2","DayWht3","DayWht4","CC2aY",
                "CC2Y1","CC2Y2","CC2Y3","CC2Y5","CC2Y6","CC2Y7",
                "CC2Y8","CC2Y9","MentHos","Ten1","Gross4a","qimd",
                "gor06","newsha","SF1","Happy","tenure","newten",
                "hhdtype","DISsex","DISeth","DISrel","DISAge",
                "DISmen","DISphy",
                "DISsori","CISRFOUR","panic","GAD","madd","OCD",
                "phob","dep","neurotic","nosymp","numdis",
                "PTSDever","MajorT16","PTSDcom","PTSDPos",
                "suicthwk","suicthyr","suicthlf","DSHlife",
                "suicatwk","suicatyr","suicatlf","DSHtry","suihfri",
                "suihhos","suihcom","suihhel","suihoth","DSH5",
                "DSHharm","DSH9","DSH10","PsycProb","Psycdis",
                "Psycdis_wt","BPDPH2","bdpd_wt","ASPDPH2","aspd_wt",
                "DVADHD1","DVADHD2","DVADHD4","scoff2","EDImpact",
                "bmigp4","DVAudit1","AUDITgp","DRNKPROB","SADQCSC",
                "SADQGP","AUDSAD2","Cannever","Cannyear","AMPHEVER",
                "AMPHYEAR","COCAEVER","CRACEVER","CRACYEAR",
                "ECSTEVER","ECSTYEAR","HEROEVER","HEROYEAR",
                "ACIDEVER","ACIDYEAR","MUSHEVER","MUSHYEAR",
                "METHEVER","METHYEAR","TRANEVER","TRANYEAR",
                "AMYLEVER","AMYLYEAR","ANABEVER",
                "ANABYEAR","GLUEEVER","GLUEYEAR","DRUGEVER",
                "DRUGYEAR","DRUGDEP",
                "DRUGDEP2","GamYR","dsmscgr","dsmprob","dsmpath",
                "numdiag","numdiag4","LCA","cluster1","cluster2",
                "cluster3","cluster4","cluster5","cluster6",
                "MedPsyc","MedDep","MedHyp","MedAnx","MedADHD",
                "anymed","Doc2Wks","DocPsyc","INQTRMEN","OUTQTRME",
                "PSYCTHER","COGTHER","ARTTHER","SOCTRAIN","MARITHER"
                ,"SEXTHER","COUNSEL","OTHTHER","OTHTHER","anyther",
                "trtment","DAYCOMYR","PSYTRTYR","PSYLGTYR",
                "CPNYR","CLDNYR","OTHNSEYR","SOCWRKYR","CPNYR",
                "ERI3","SFQA","SFQB","SFQC","SFQD",
                "SFQE","SFQF","SFQG","SFQH","DLSS4","DLSS5",
                "PrimGrp","ChldInst","LACare","BothMaPa",
                "YNotBoth","MaOrPa","AnyChild","NoChild",
                "InDebt1","InDebt6",
                "SFHELPYR","HMHELPYR","OREACHYR","anyccar","anyhlca"
                ,"anydaca","wt_ints1","ipsu_0714","istrata_0714","eqvinc5",
                "ptsdlong","PTSDarms","MajorT16") %>%
  janitor::clean_names() %>%
  janitor::remove_empty("cols") %>%
  janitor::remove_empty("rows") %>%
  mutate(across(where(is.factor), as.character))

head(subset_pms07, 5)


# Arrange alphabetically and make 'colnames' lowercase

subset_pms07 <-subset_pms07[,order(colnames(subset_pms07))] %>% rename_all(tolower)

# Check names
head(subset_pms07, 5)
table(subset_pms07$diag)
class(subset_pms07$diag)

# remove source df
remove(source_pms07)

table(subset_pms07$diag)
```

```{r convert}

# Convert unwanted levels to NA
# write out all the offending strings of different NAs used
na_strings <- c("No answer/refused",
                "Don't know",
                "Missing data",
                "Proxy",
                "Item not applicable",
                "No disord",
                "Don't know",
                "Item not applicable")

#Then you write ~.x %in% na_strings - which reads as “does this 
#value occur in the list of NA strings”.
subset_pms07 %>%
  replace_with_na_all(condition = ~.x %in% na_strings)


# convert df back to factor 
subset_pms07 %>% mutate_if(is.character, as.factor)

```

```{r overall descriptive tbl}
# Big desc table
subset_pms07 %>%
  select(age10yr, res_sex, diag, dvilo4a) %>%
  tbl_summary(by = age10yr) %>%
  add_overall() %>%
  add_n() %>%
  bold_labels()

```

```{r univariate plots}
#### Univariate Plots ####

# Age
# change y to counts + add counts to bar + add n = 
subset_pms07 %>%
  drop_na() %>% # get rid of na from plot
  ggplot(aes(x = (age10yr),
      y = prop.table(stat(count)),
      fill = fct_infreq(age10yr),
      label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + # make y % and no decimal
  labs(title = "Survey Makeup (2007) \n by Age Group", 
       x = 'Respondant Age Group', 
       y = 'Percentage',
       fill = 'Age Group',
       caption = "(Test Footnote 2021)") + # footnote
  annotate("text", x = 7, y = .2, size = 3, label = "n = 7,403") + # add total n = manually
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) # 0 = left, 0.5 = middle, 1 = right

# Find total of variable 
tabsum <- table(subset_pms07$diag)
addmargins(tabsum)

7403 - 6126

# Renaming factor levels dplyr
subset_pms07$diag <- recode_factor(subset_pms07$diag, 
                                   "sev dep ep" = "Sev Dep",
                                   "mild dep ep" = "Mild Dep",
                                   "mod dep ep" = "Mod Dep",
                                   "panic" = "Panic",
                                   "social phob" = "Soc Phob",
                                   "Spec iso phob" = "Specific Phob")

# Common Mental Disorder Groups
subset_pms07 %>%
filter(diag != 'No disord') %>% # drop fct levels you dont want shown
  drop_na() %>%
  ggplot(aes(x = fct_infreq(diag),
             y = prop.table(stat(count)),
             fill = fct_infreq(diag),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup (2007) \n by Common Mental Disorder Group", 
       x = 'Respondant CMD Group', 
       y = 'Percentage',
       fill = 'Condition',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 9.3, y = .55, size = 3, label = "(total n = 7,403)") +
  annotate("text", x = 9.3, y = .50, size = 3, label = "n = 1,277") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5))

# Find total of variable 
tabsum <- table(subset_pms07$cc2a_y)

addmargins(tabsum)
# Recieved Community Care in Last Year
subset_pms07 %>%
  filter(cc2a_y != "Don't know") %>% 
  drop_na() %>%
  ggplot(aes(x = fct_infreq(cc2a_y),
             y = prop.table(stat(count)),
             fill = fct_infreq(cc2a_y),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup (2007) \n by Reciept of Community Care", 
       x = 'Recieved Care', 
       y = 'Percentage',
       fill = 'Care Group',
       caption = "(Test Footnote 2021)") +
  annotate("text", x = 2.3, y = .9, size = 3, label = "(total n = 7,403)") +
  annotate("text", x = 2.3, y = .8, size = 3, label = "n = 7,402") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5))


# Renaming factor levels dplyr
subset_pms07$dvilo4a <- recode_factor(subset_pms07$dvilo4a, 
                                   "In employment not unpaid family worker" = "Employed")
# Employement Status
subset_pms07 %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(dvilo4a),
             y = prop.table(stat(count)),
             fill = fct_infreq(dvilo4a),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup (2007) \n by Employment Status", 
       x = 'Respondant Status', 
       y = 'Percentage',
       fill = 'Employment Type',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 4, y = .6, size = 3, label = "(total n = 7,403)") +
  annotate("text", x = 4, y = .5, size = 3, label = "n = 7,402") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5))


# Equivalised income quintiles
subset_pms07 %>%
  filter(eqvinc5 != "Item not applicable") %>% 
  drop_na() %>%
  ggplot(aes(x = (eqvinc5),
             y = prop.table(stat(count)),
             fill = fct_infreq(eqvinc5),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup (2007) \n by Equivalised income quintiles",
       x = 'Equivalised income quintiles', 
       y = 'Percentage',
       fill = 'Income Quintile',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 5, y = .3, size = 3, label = "n = 5,872") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) 


# Ethnic Group
subset_pms07 %>%
  filter(!ethnic5 %in% c("Don't know", "No answer/refused")) %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(ethnic5),
             y = prop.table(stat(count)),
             fill = fct_infreq(ethnic5),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(title="Survey Makeup \n by Ethnic Group (2007)", 
       x = 'Respondant Ethnic Group', 
       y = 'Percentage',
       fill = 'Ethnic Group',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 5.5, y = .9, size = 3, label = "n = 5,353") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) 


# Highest Qualification
subset_pms07 %>%
  filter(!edqual5 %in% c("Don't know", "No answer/refused")) %>% # drop more than 2 levels
  drop_na() %>%
  ggplot(aes(x = fct_infreq(edqual5),
             y = prop.table(stat(count)),
             fill = fct_infreq(edqual5),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup \n by Qualification (2007)", 
       x = 'Respondant Highest Qualification', 
       y = 'Percentage', fill = 'Qualification',
       caption = "(Test Footnote 2021)") +
  annotate("text", x = 6.5, y = .4, size = 3, label = "n = 7,235") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5))

# Marital Status
subset_pms07 %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(res_mar_df),
             y = prop.table(stat(count)),
             fill = fct_infreq(res_mar_df),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup (2007) \n by Marital Status", 
       x = 'Respondant Status', 
       y = 'Percentage', fill = 'Marital Status',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 6, y = .5, size = 3, label = "n = 7,235") +
theme(plot.caption = element_text(hjust = 0),
      plot.title = element_text(hjust = 0.5)) 


# Number of Common Mental Disorders
subset_pms07 %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(numdis),
             y = prop.table(stat(count)),
             fill = fct_infreq(numdis),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title = "Survey Makeup (2007) \n by Number of CMDs Diagnosed", 
       x = 'Respondant Amount', 
       y = 'Percentage',
       fill = 'Number of CMD',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 3.3, y = .9, size = 3, label = "n = 7,403") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5))

# Find total of variable 

# Region
subset_pms07 %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(gor06),
             y = prop.table(stat(count)),
             fill = fct_infreq(gor06),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) +
  coord_flip() +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
 labs(title="Survey Makeup (2007) \n by Region", 
       x = 'Respondants by Region', 
       y = 'Percentage',
      fill = 'Region',
      caption = "(Test Footnote 2021)") + 
  annotate("text", x = 9.5, y = .16, size = 3, label = "n = 7,403") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) 


# Treatment for CMDs
subset_pms07 %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(trtment),
             y = prop.table(stat(count)),
             fill = fct_infreq(trtment),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(title="Survey Makeup (2007) \n by CMD Treatment (2007)", 
       x = 'Treatment Group', 
       y = 'Percentage',
       fill = 'Treatment',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 5, y = 1, size = 3, label = "n = 7,382") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5))


# Sex
subset_pms07 %>%
  drop_na() %>%
  ggplot(aes(x = fct_infreq(res_sex),
             y = prop.table(stat(count)),
             fill = fct_infreq(res_sex),
             label = scales::percent(prop.table(stat(count))))) +
  geom_bar() + 
  geom_text(stat = 'count',
            position = position_dodge(.9), 
            vjust = -0.5, 
            size = 3) + 
  scale_y_continuous(labels = scales::percent) +
  labs(title="Survey Makeup (2007)\n by Sex", 
       x = 'Respondant Sex', 
       y = 'Percentage',
       fill = 'Sex',
       caption = "(Test Footnote 2021)") + 
  annotate("text", x = 2.3, y = .7, size = 3, label = "n = 7,403") +
  theme(plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5)) 

```
```{r cross tab}
# cross tab ex
#tbl_cross_ex2 <-
#  subset_pms07 %>%
#  tbl_cross(row = res_age, col = diag, percent = "cell") %>%
# add_p()
```

```{r model example}

# example model for code
# regression - provide model
mod1 <- glm(dvilo4a ~ diag + age10yr + edqual5,
            data = subset_pms07,
            family = binomial()
)

mod1 %>% 
  tbl_regression(exponentiate = TRUE) %>%
  bold_labels() %>%
  bold_p(t = .1)

```

